### ISSUE TITLE
/f map problem

### ISSUE THREAD

**Issue by antonin78** [MassiveCraft/Factions#956] opened 2015-10-19 20:06 UTC
Here is a error code when a player executes the /f map command.

>> http://pastebin.com/nY2V9jCN
>> here's a timings: http://timings.aikar.co/?url=12865957

>> here's the code directly pasted

[15:21:39] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f map' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[spigot.jar:git-PaperSpigot-e8e85d7]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:766) ~[spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1046) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:883) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:790) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:638) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-PaperSpigot-e8e85d7]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-e8e85d7]
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by ulumulu1510** [comment] 2015-10-20 19:15
Please provide the full error log (pastebinned isprefectly fine), this is only half of it. Also please state your:
*Factions version
*MassiveCore version
*Spigot version

**Comment by antonin78** [comment] 2015-10-20 21:36
I'll give you the complete error code asap.

Here are my versions:

Factions: 2.8.0
MCore: 2.8.0
Spigot: PaperSpigot a8e85d7 1.7.10 (Protocol 1.7/1.8)

See you tomorrow for the rest of the code. :)

**Comment by MarkehMe** [comment] 2015-10-26 02:43
@antonin78 any update on that error log?

**Comment by magnusulf** [comment] 2015-12-22 14:11
Duplicate of #218

**Closed by magnusulf** 2015-12-22 14:11 UTC
Labels: Incomplete
