### ISSUE TITLE
NullPointerException in factions 2.8.1

### ISSUE THREAD

**Issue by luniso** [MassiveCraft/Factions#959] opened 2015-10-29 18:45 UTC
I found that error in my console, any idea?
http://pastebin.com/XEgQPHYW

**Comment by ulumulu1510** [comment] 2015-10-30 13:13
Please state your versions of:
* MassiveCore 
* Factions
* spigot/bukkit

**Comment by luniso** [comment] 2015-10-30 23:21
MassiveCore 2.8.1
Factions 2.8.1
spigot 1.8.8

**Comment by ulumulu1510** [comment] 2015-11-03 08:40
Could you update to the latest version 2.8.2? That would help with searching for the nullpointer.

Under which circumstances has this error happened? Because it seems that somehow we got a nullpointer exception when it is very unlikely to have one.

**Comment by magnusulf** [comment] 2015-11-10 08:02
You should first of all update to Factions 2.8.2.
It seems the issue is caused because of an invalid MConf. Try and delete your MConf (then reconfigure where necessary).

**Comment by ulumulu1510** [comment] 2016-01-16 18:53
As the issue has been found and not been reported back, I assume the issue is resolved. Closing.

**Closed by ulumulu1510** 2016-01-16 18:53 UTC
Labels: Bug
