### ISSUE TITLE
[Factions + Mods/Forge/Kcauldron]

### ISSUE THREAD

**Issue by Andrew2070** [MassiveCraft/Factions#1139] opened 2016-08-01 14:06 UTC
Hi.

I have a Custom ModPack server built to use Factions.
However, The Configuration does say we can replace container/door etc arrays to work with forge.
What I am confused is how is it that I place these blocks in to have them protected?

The default configuration for the Container array is as follows:
"materialsContainer": [
"DISPENSER",
"CHEST",
"FURNACE",
"BURNING_FURNACE",
"JUKEBOX",
"BREWING_STAND",
"ENCHANTMENT_TABLE",
"ANVIL",
"BEACON",
"TRAPPED_CHEST",
"HOPPER",
"DROPPER"
],

Now How do i list another mod's items in there?
By Id? Name? id/name? what about metadata?

Just a few things I would like to know because I have invested a lot in this server and do not wish to make identical with 1000k other servers using MyTown and MyTown 2 for protection.

For future reference, what about possible forge support like MyTown, where users can create custom built protection json files that are used by Factions to protect from modded lands?

Anyhow, would love if my first question regarding customizing the configuration could be given a reply.

Thanks!

**Comment by Andrew2070** [comment] 2016-08-01 14:55
config: http://pastebin.com/CxXCkyex

**Comment by Andrew2070** [comment] 2016-08-03 13:43
bump?

**Comment by MarkehMe** [comment] 2016-08-04 06:46
Duplicate of #940

**Closed by MarkehMe** 2016-08-04 06:46 UTC
