### ISSUE TITLE
tnt and creeper bug

### ISSUE THREAD

**Issue by PerryGamerPT** [MassiveCraft/Factions#1117] opened 2016-06-27 20:10 UTC
hello my name is PerryGamerPT and i have a factions server and i use yours plugin. i love the plugin but have one bug in some factions.
If i use one tnt  along the base of the other factions and i active, give me damage and in blocks outside the protection of the faction. And creepers is the same. please helpme i cant open my server because tthe bases are impenetrable. Thank answer is a solution.

**Comment by ulumulu1510** [comment] 2016-06-27 20:36
This is probably a duplicate of 	https://github.com/MassiveCraft/Factions/issues/1107
If not, you can find configuration advice in there aswell, which should solve your problem.

**Closed by ulumulu1510** 2016-06-27 20:36 UTC
