### ISSUE TITLE
Question about submittig PRs

### ISSUE THREAD

**Issue by ItsMonkeyyy** [MassiveCraft/Factions#1040] opened 2016-02-29 04:25 UTC
Hello, I tend to make many PRs onto FactionsUUID and I decided to look through MassiveCraft's original branch. I have seen that the code for this branch of Factions is in Allman
```
public void someMethod()
{
   //code
}
```

My question is, is it neccessary to follow these conventions? Are there any other conventions that I need to follow if I submit a PR? Thanks.

**Comment by ulumulu1510** [comment] 2016-02-29 09:01
Thank you for considering to submit a PR :)
The MassiveCraft Team does indeed follow certain Tech-Standards which can be found here:
https://www.massivecraft.com/tech-standards

If you use Eclipse, you can import the Allman-style that is downloadable on the page I just provided you.

It is indeed necessary to follow these conventions. We strive for code with splendid quality and readability, thus it the whole codebase needs to follow the same style.

One other thing you need to know is that we work in Iterations. We do this to ensure code-quality and to learn from each other. That means:

- 1) You Fork Factions, make a new branch with your Fix/Feature addition, code, test and then notify us with a PR or through skype that it is ready for an iteration.
- 2) We then give feedback on your PR/commit through the line comment feature.
- 3) You then apply this feedback to your commit.
- 4) We repeat the steps 2 and 3 till your commit is ready to be pulled :)

We are just trying to clean up the bugs in our issue tracker, so you are more welcome to help us out :) I hope to hear from you soon.

**Comment by MarkehMe** [comment] 2016-02-29 11:28
A nice tip is to keep your feature to one commit as well. You can do this by forking Factions, then creating a new branch. Use this branch as your feature branch and stick to one commit that you amend on after feedback. 

Sounds really daunting at first! But it's actually fairly simple. :+1: Give us a shout if you need help!

**Comment by ItsMonkeyyy** [comment] 2016-02-29 13:47
Thanks for the quick responses @ulumulu1510 & @MarkehMe I will keep everything you said in mind.

**Comment by ItsMonkeyyy** [comment] 2016-03-01 23:21
@ulumulu1510 I use the IntelliJ IDE because of personal preferences, so I was wondering if it was possible to get the Indent Style for IntelliJ. Thanks.

**Comment by ulumulu1510** [comment] 2016-03-02 05:48
I am also using intellij. I will take a look if I can export the indent style Ii have configured, but otherwise you might just be able to configure intellij to do the brackets on the same line (and others) yourself  :)

**Comment by ulumulu1510** [comment] 2016-03-02 18:52
@ItsMonkeyyy 
https://drive.google.com/file/d/0BxKR-QugBXv_TnI3bGNTb3JjU2c/view?usp=sharing

Here you go. I put the codestyle on google drive for you to download. Simply head to settings > editor > codestyle > java > manage and then import this style.

**Comment by ItsMonkeyyy** [comment] 2016-03-02 22:06
@ulumulu1510 thanks a lot! One final question though. I saw the issues marked as 'bug' and they're all pretty old. Should I still consider them? Thanks.

**Comment by ulumulu1510** [comment] 2016-03-02 22:13
If we could talk more openly what bug you want to target, that would be helpfull for the situation I think :)

Frankly, yes. Even very old bugs can still be valid. Take the /f map bug for instance. It's not easy to reproduce (because you need over 60 factions in a very close proximity to each other), but the bug is fairly obvious in the code. the solution to it however is not so obvious. I myself am working on that one, which doesn't mean you can't. (we want to learn from each other, you might find something I didn't and vice versa).

Even old bugs have to be fixed ;)
I'll write you an email so we can exchange skype contacts, if that is alright for you ofc.

**Comment by ItsMonkeyyy** [comment] 2016-03-02 22:14
@ulumulu1510 sure I do not mind, I'll reply with my skype username as well :)

**Comment by ulumulu1510** [comment] 2016-03-02 22:18
Email sent :)

**Comment by ulumulu1510** [comment] 2016-03-05 18:51
Contact has been established, issue is thus resolved. Closing :)

**Closed by ulumulu1510** 2016-03-05 18:51 UTC
