### ISSUE TITLE
Disband Errors

### ISSUE THREAD

**Issue by gh0ztbuster** [MassiveCraft/Factions#868] opened 2015-05-23 18:12 UTC
Disband Errors

Plugins:
* Vault 1.5.3
* CraftConomy 3.2.1
* Factions 2.7.5
* MassiveCore 2.7.5
Mstore:
* MongoDB

I do not use Factions Money on my server

```
[11:06:30] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;33;1msetFactionId moved [0;35;1m50894b3d-8677-4c3f-8537-b88d5d42acc0 [0;33;1maka [0;35;1m[0;37;1mGoldpwner [0;33;1mfrom [0;35;1mnone [0;33;1maka [0;35;1m[0;32;22mWilderness [0;33;1mto [0;35;1m871c78dd-7d55-409c-b5b3-37b62477c3b9 [0;33;1maka [0;35;1mZEUZ[0;33;1m.[m
[11:06:30] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1mGoldpwner joined the faction ZEUZ.[m
[11:06:36] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;37;1mGoldpwner kicked xsplazex from the faction ZEUZ[m
[11:06:36] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1mThe faction ZEUZ (871c78dd-7d55-409c-b5b3-37b62477c3b9) has been disbanded since it has no members left.[m
[11:06:36] [Server thread/INFO]: [0;33;1mThe faction [0;37;1mZEUZ[0;33;1m was disbanded.[m
[11:06:36] [Server thread/WARN]: java.sql.SQLException: Subquery returns more than 1 row
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[11:06:36] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[11:06:36] [Server thread/WARN]: 	at com.greatmancode.com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
[11:06:36] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:345)
[11:06:36] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:166)
[11:06:36] [Server thread/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:310)
[11:06:36] [Server thread/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:130)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:173)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:63)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinAbstract.set(MoneyMixinAbstract.java:138)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.Money.set(Money.java:241)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:68)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.preDetach(Coll.java:425)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.detach(Coll.java:389)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.detachEntity(Coll.java:366)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:66)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.factions.entity.Faction.promoteNewLeader(Faction.java:1126)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.factions.cmd.CmdFactionsKick.perform(CmdFactionsKick.java:91)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:327)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349)
[11:06:36] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67)
[11:06:36] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:06:36] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[11:06:36] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[11:06:36] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[11:06:36] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[11:06:36] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11:06:36] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f kick xsplazex' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_76]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_76]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: com.greatmancode.craftconomy3.utils.BackendErrorException: Subquery returns more than 1 row
	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:350) ~[?:?]
	at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:166) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:310) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:130) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:173) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:63) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.set(MoneyMixinAbstract.java:138) ~[?:?]
	at com.massivecraft.massivecore.money.Money.set(Money.java:241) ~[?:?]
	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:68) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.preDetach(Coll.java:425) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.detach(Coll.java:389) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.detachEntity(Coll.java:366) ~[?:?]
	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:66) ~[?:?]
	at com.massivecraft.factions.entity.Faction.promoteNewLeader(Faction.java:1126) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsKick.perform(CmdFactionsKick.java:91) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:327) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	... 14 more
[11:06:50] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;37;1mGoldpwner kicked xsplazex from the faction ZEUZ[m
[11:06:50] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1mThe faction ZEUZ (871c78dd-7d55-409c-b5b3-37b62477c3b9) has been disbanded since it has no members left.[m
[11:06:50] [Server thread/INFO]: [0;33;1mThe faction [0;37;1mZEUZ[0;33;1m was disbanded.[m
[11:06:50] [Server thread/WARN]: java.sql.SQLException: Subquery returns more than 1 row
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
[11:06:50] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
[11:06:50] [Server thread/WARN]: 	at com.greatmancode.com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
[11:06:50] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:345)
[11:06:50] [Server thread/WARN]: 	at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:166)
[11:06:50] [Server thread/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:310)
[11:06:50] [Server thread/WARN]: 	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:130)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:173)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:63)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.MoneyMixinAbstract.set(MoneyMixinAbstract.java:138)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.money.Money.set(Money.java:241)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:68)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.preDetach(Coll.java:425)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.detach(Coll.java:389)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Coll.detachEntity(Coll.java:366)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:66)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.factions.entity.Faction.promoteNewLeader(Faction.java:1126)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.factions.cmd.CmdFactionsKick.perform(CmdFactionsKick.java:91)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:327)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349)
[11:06:50] [Server thread/WARN]: 	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67)
[11:06:50] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[11:06:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13)
[11:06:50] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
[11:06:50] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651)
[11:06:50] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554)
[11:06:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[11:06:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f kick xsplazex' in com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1133) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:968) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_76]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_76]
	at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: com.greatmancode.craftconomy3.utils.BackendErrorException: Subquery returns more than 1 row
	at com.greatmancode.craftconomy3.storage.sql.SQLStorageEngine.setBalance(SQLStorageEngine.java:350) ~[?:?]
	at com.greatmancode.craftconomy3.account.Account.deposit(Account.java:166) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:310) ~[?:?]
	at net.milkbowl.vault.economy.plugins.Economy_Craftconomy3.depositPlayer(Economy_Craftconomy3.java:130) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:173) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:63) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.set(MoneyMixinAbstract.java:138) ~[?:?]
	at com.massivecraft.massivecore.money.Money.set(Money.java:241) ~[?:?]
	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:68) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.preDetach(Coll.java:425) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.detach(Coll.java:389) ~[?:?]
	at com.massivecraft.massivecore.store.Coll.detachEntity(Coll.java:366) ~[?:?]
	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:66) ~[?:?]
	at com.massivecraft.factions.entity.Faction.promoteNewLeader(Faction.java:1126) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsKick.perform(CmdFactionsKick.java:91) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:327) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:306) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCommand.execute(MassiveCommand.java:349) ~[?:?]
	at com.massivecraft.massivecore.cmd.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:67) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-d35-1.8.3.jar:git-Spigot-0b997a9-30d751b]
	... 14 more
[11:08:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1mGoldpwner left the faction: ZEUZ[m
[11:08:23] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;33;1msetFactionId moved [0;35;1m50894b3d-8677-4c3f-8537-b88d5d42acc0 [0;33;1maka [0;35;1m[0;37;1mGoldpwner [0;33;1mfrom [0;35;1m871c78dd-7d55-409c-b5b3-37b62477c3b9 [0;33;1maka [0;35;1mZEUZ [0;33;1mto [0;35;1mnone [0;33;1maka [0;35;1m[0;32;22mWilderness[0;33;1m.[m
[11:08:26] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;33;1msetFactionId moved [0;35;1m50894b3d-8677-4c3f-8537-b88d5d42acc0 [0;33;1maka [0;35;1m[0;37;1mGoldpwner [0;33;1mfrom [0;35;1mnone [0;33;1maka [0;35;1m[0;32;22mWilderness [0;33;1mto [0;35;1mecc43d47-c21a-4b8e-a090-080b7f1d8aea [0;33;1maka [0;35;1mdead[0;33;1m.[m
[11:08:26] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1mGoldpwner created a new faction: dead[m
[11:08:28] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;33;1mThe faction [0;35;1mdead [0;33;1m([0;35;1mecc43d47-c21a-4b8e-a090-080b7f1d8aea[0;33;1m) was disbanded by [0;35;1m[0;37;1mGoldpwner[0;33;1m.[m
[11:08:29] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;31;1mNon existing factionId [0;35;1mecc43d47-c21a-4b8e-a090-080b7f1d8aea [0;31;1mrequested. [0;33;1mCleaning all boards and mplayers.[m
[11:08:29] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 2.7.5[0;36;22m] [0;33;1m[0;33;1msetFactionId moved [0;35;1m50894b3d-8677-4c3f-8537-b88d5d42acc0 [0;33;1maka [0;35;1m[0;37;1mGoldpwner [0;33;1mfrom [0;35;1mNULL [0;33;1maka [0;35;1mNULL [0;33;1mto [0;35;1mnone [0;33;1maka [0;35;1m[0;32;22mWilderness[0;33;1m.[m

```

**Comment by magnusulf** [comment] 2015-05-23 18:33
The problem seems to be in craftconomy.

**Comment by gh0ztbuster** [comment] 2015-05-23 19:29
I don't want craftconomy to be involved in factions at all. Is there a way to disable massivecraft vault economy bridge?

**Comment by magnusulf** [comment] 2015-05-23 20:22
Disable it in the MConf.

**Comment by gh0ztbuster** [comment] 2015-05-24 03:33
This error occurred while:

"econEnabled": false

**Comment by gh0ztbuster** [comment] 2015-05-24 03:36
EDIT: CraftConomy also keeps registering faction UUID economy balances even though I have disabled the feature.

**Comment by haloman30** [comment] 2015-06-28 22:06
I have also been getting this error, and econEnabled is false for me as well.

**Comment by gh0ztbuster** [comment] 2015-07-18 04:48
I use craftconomy

**Comment by ulumulu1510** [comment] 2016-01-16 18:49
This problem references: https://github.com/MassiveCraft/Factions/issues/385

But is not the same. Developers note: This can be fixed by changing Money to Econ here:
https://github.com/MassiveCraft/Factions/blob/master/src/com/massivecraft/factions/entity/Faction.java#L69

**Comment by magnusulf** [comment] 2016-01-24 19:12
Although not the same symptom, the underlying bug is the same. Duplicate of #385

**Closed by magnusulf** 2016-01-24 19:12 UTC
Labels: Confirmed, Urgent

**Comment by DraksterAU** [comment] 2016-03-18 16:30
@magnusulf I just saw this bug in econLandRewardRoutine which caused immense lag on my server for the last few hours.

Happened almost immediately after a player who had changed his name rejoined the server, not sure if it is an issue still.

I'm using Factions 2.8.6, CraftConomy 3.2.1 and Vault 1.4.1 (1.7.10).
