### ISSUE TITLE
Inactive power lose

### ISSUE THREAD

**Issue by Murdox1221** [MassiveCraft/Factions#459] opened 2013-10-13 09:16 UTC
I saw a ticket was already submitted, but from what I see it went no where. I would like to see if an option to have players lose power if they become inactive. I know this was an option in the 2.0 branch however It is not in the 2.1 branch. 

As always thank you.

**Comment by magnusulf** [comment] 2015-12-22 14:02
Duplicate of #368

**Closed by magnusulf** 2015-12-22 14:02 UTC
