### ISSUE TITLE
Russian Translate

### ISSUE THREAD

**Issue by CeleDKo** [MassiveCraft/Factions#1242] opened 2017-07-07 14:27 UTC
Hi, I would like to make a Russian translation for the Factions plugin, but I do not understand where I find the lang files to do this.

**Comment by imaBASKET** [comment] 2017-07-07 16:25
I believe you're going to have to fork the plugin and edit the .java files because there is no lang file which all the commands and actions that send messages are pulled from, but rather the messages/text are located directly in the .java files pertaining to whatever action or command the file is named after in most cases.

See this if you are having trouble or don't get what I mean:
https://github.com/MassiveCraft/Factions/issues/1209

**Comment by MarkehMe** [comment] 2017-07-20 11:29
This is a duplicate of #1032 - a longest requested feature!

**Closed** 2017-07-20 11:29 UTC
