### ISSUE TITLE
Feature Request: Relationship cooldown

### ISSUE THREAD

**Issue by MaxCoffeebreath** [MassiveCraft/Factions#442] opened 2013-10-02 22:22 UTC
I'd like to see a relationship cooldown timer to prevent abusing fast changes to relationships.

Example, two factions are currently in truce.  Faction B changes to enemy, kills members of faction A, then changes back to truce to engage friendly fire.

Example, faction A asks for alliance with faction B under false pretense.  After allying, they grief faction B then set relationship back to anything except alliance to prevent retaliation in kind.

On my server I'd set the cooldown to 30 minutes, so you set a new relationship status you can't change that for 30 min.

**Comment by magnusulf** [comment] 2015-12-23 22:57
Duplicate of #37

**Closed by magnusulf** 2015-12-23 22:57 UTC
