### ISSUE TITLE
Factions-Error

### ISSUE THREAD

**Issue by BrojectOne** [MassiveCraft/Factions#1049] opened 2016-03-16 14:13 UTC
Hi,
Factions is actually working on our server (almost latest Spigot 1.9-Version, latest Factions- and MassiveCore-Builds), but when starting the server, this happens:

**[IMPORTANT: read from bottom to top!]**

16.03 14:53:27 [Multicraft] Skipped 65 lines due to rate limit (30/s) 
16.03 14:53:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72] 
16.03 14:53:25 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72] 
16.03 14:53:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72] 
16.03 14:53:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72] 
16.03 14:53:25 [Server] INFO at com.massivecraft.factions.engine.EngineMain.blockExplosion(EngineMain.java:1225) ~[?:?] 16.03 14:53:25 [Server] INFO at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:308) ~[?:?] 16.03 14:53:25 [Server] INFO at com.massivecraft.massivecore.ps.PS.valueOf(PS.java:296) ~[?:?] 16.03 14:53:25 [Server] INFO at com.massivecraft.massivecore.ps.PS.<init>(PS.java:253) ~[?:?] 16.03 14:53:25 [Server] INFO at com.massivecraft.massivecore.ps.PS.throwIfStrange(PS.java:269) ~[?:?] 
16.03 14:53:25 [Server] INFO Caused by: java.lang.IllegalArgumentException: Location X should not be NaN! 16.03 14:53:25 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:628) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1420) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.World.g(World.java:1580) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1605) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:243) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1761) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.EntityEnderDragon.n(EntityEnderDragon.java:287) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at net.minecraft.server.v1_9_R1.EntityEnderDragon.b(EntityEnderDragon.java:433) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9-selbstgemacht.jar:git-Spigot-6f291ea-55a8535] 
16.03 14:53:25 [Server] INFO org.bukkit.event.EventException 
16.03 14:53:25 [Server] ERROR Could not pass event EntityExplodeEvent to Factions v2.8.7Beta

**Comment by BrojectOne** [comment] 2016-03-16 14:20
Ok, sorry, i just found out that somebody else pasted and solved this problem already!

**Comment by ulumulu1510** [comment] 2016-03-16 14:20
Duplicate of https://github.com/MassiveCraft/Factions/issues/1044 to redirect people

**Closed by ulumulu1510** 2016-03-16 14:20 UTC
