### ISSUE TITLE
Factions Commands

### ISSUE THREAD

**Issue by KingJayeh** [MassiveCraft/Factions#1057] opened 2016-03-24 04:02 UTC
In factions 2.8.7 Beta the commands where messes up is when you do /f truce or /f enemy or /f ally or anything relation and in chat when it says [Accept] the command is /set truce [factionname] but that doesnt work so /f truce [factionname] or what ever it  is

**Comment by MarkehMe** [comment] 2016-03-24 05:25
This appears to be a duplicate of #1048

**Closed by MarkehMe** 2016-03-24 05:25 UTC
