### ISSUE TITLE
Not Working Help

### ISSUE THREAD

**Issue by CabbageIzSavage** [MassiveCraft/Factions#1230] opened 2017-06-13 09:51 UTC
## Affected Plugin
- **Affected Plugin Name:** 
- **Affected Plugin Version:** 2.8.0
- **MassiveCore Version:** 2.8.0

## Describe your environment

- **Spigot version:** Thermos 1.7.10
- **Config pastebin:** 

## Steps to reproduce this bug

  1. First I did /f create Mosquilly (my team name)
  2. Next I did /f claim one 
  3. Finally it said to report it on here

**Observed results**
I wasn't able to claim land and it said to report it here, I am using a Mac OS X and I launched it on Technic.

**Expected results**
I should have claimed it.

**Comment by magnusulf** [comment] 2017-06-15 13:20
I am afraid we don't have a fix for this bug for modded servers. Just FYI.

**Comment by MarkehMe** [comment] 2017-06-22 06:54
Duplicate of #940

**Closed by MarkehMe** 2017-06-22 06:54 UTC
