### ISSUE TITLE
Set perms per chunk

### ISSUE THREAD

**Issue by AlHollandiyah** [MassiveCraft/Factions#830] opened 2015-03-04 19:45 UTC
I would like to request a feature if it is possible to implement it. I would love to be able to toggle the perms for groups (for example allies) per chunk, aside from being able to toggle it for the whole faction. Think for example of a faction claim where u want allies to be able to use a part of your land, but not be able to build on other parts. Something like /f perm YOURFACTION chunk build ally no, for example.

**Comment by iGeek99** [comment] 2015-03-10 01:54
Yes, I would love to see this happen. I would like members to be able to build and use chests in one area, but not build and use chests in another.

**Comment by ashower** [comment] 2015-03-15 20:01
Are you aware about /f access and the ability to grant access per player or per faction?

**Comment by iGeek99** [comment] 2015-03-16 14:33
Yes there is no way to use current access to enable this. I've tried every possible way.

**Comment by AlHollandiyah** [comment] 2015-03-16 15:33
As far as I understood /f acces is used to make areas of the faction that only the faction owner and specified faction members can acces. But what I am looking for is how to toggle other perms (not acces, but in this case build or farming rights), and for allies instead of members. /f acces does none of this.

**Comment by ulumulu1510** [comment] 2016-01-16 18:45
duplicate off: https://github.com/MassiveCraft/Factions/issues/443

**Closed by ulumulu1510** 2016-01-16 18:45 UTC
