### ISSUE TITLE
Ender Pearls

### ISSUE THREAD

**Issue by CurtainHumper** [MassiveCraft/Factions#1177] opened 2017-01-05 11:26 UTC
Can I disable the use of ender pearls in a hostile faction terretory?
So people can't just hop over walls by using pearls.
Thanks.

**Comment by Uranusak** [comment] 2017-02-02 12:29
and >> http://minecraft.gamepedia.com/Chorus_Fruit

**Comment by MarkehMe** [comment] 2017-03-12 10:06
Duplicate of #139

**Closed by MarkehMe** 2017-03-12 10:06 UTC
Labels: Feature
