### ISSUE TITLE
/f map -- ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Write** [MassiveCraft/Factions#810] opened 2015-02-16 07:00 UTC
Error when calling /f map. It seems to happen only after chunk were claimed. On terrain they are only few claims it seems to work. 

http://pastebin.com/XcX9rEGt

**Comment by oloflarsson** [comment] 2015-02-21 12:24
In that area; are there loads of different factions nearby? Say about 65 of them or more?

**Comment by Write** [comment] 2015-02-26 18:00
Yup, exactly that.

**Comment by Write** [comment] 2015-04-05 00:11
Update ?

**Comment by Write** [comment] 2015-04-16 10:39
... ?

**Comment by Write** [comment] 2015-05-10 18:19
:/

**Comment by Write** [comment] 2015-11-26 08:28
Stillll waitiiiing...

**Comment by MarkehMe** [comment] 2015-11-27 07:33
Are you still getting this issue?

**Comment by magnusulf** [comment] 2015-11-27 10:18
Simply put, MAP_KEY_CHARS is too short. We'll have to make the array larger to avoid this situation (or rework parts of the /f map command).

**Comment by magnusulf** [comment] 2015-12-22 14:10
Duplicate of #218

**Closed by magnusulf** 2015-12-22 14:10 UTC
