### ISSUE TITLE
Factions 2.7.5 (Plugin Factions v2.7.5 generated an exception while executing task 14084

### ISSUE THREAD

**Issue by xtomyserrax** [MassiveCraft/Factions#764] opened 2015-01-02 03:06 UTC
Hey, this warn spams you all the console:

[21:50:00] [pool-3-thread-17/WARN]: Exception in thread "pool-3-thread-17" 
[21:50:00] [pool-3-thread-17/WARN]: org.apache.commons.lang.UnhandledException: Plugin Factions v2.7.5 generated an exception while executing task 14084
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOfflinePlayer(Ljava/util/UUID;)Lorg/bukkit/OfflinePlayer;
	at com.massivecraft.massivecore.mixin.PlayedMixinDefault.getFirstPlayed(PlayedMixinDefault.java:28)
	at com.massivecraft.massivecore.mixin.Mixin.getFirstPlayed(Mixin.java:186)
	at com.massivecraft.massivecore.store.SenderEntity.getFirstPlayed(SenderEntity.java:107)
	at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.applyPlayerAgeBonus(EventFactionsRemovePlayerMillis.java:70)
	at com.massivecraft.factions.event.EventFactionsRemovePlayerMillis.<init>(EventFactionsRemovePlayerMillis.java:53)
	at com.massivecraft.factions.entity.MPlayer.getRemovePlayerMillis(MPlayer.java:693)
	at com.massivecraft.factions.entity.MPlayer.considerRemovePlayerMillis(MPlayer.java:709)
	at com.massivecraft.factions.entity.MPlayerColl$1.run(MPlayerColl.java:62)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

It starts with a small number of task and then bigger.

Please fix it, i cant download bigger versions of bukkit/spigot

" https://github.com/MassiveCraft/Factions/issues/745  "

**Comment by oloflarsson** [comment] 2015-01-04 10:28
Duplicate of #745.
Anyone can obtain Spigot 1.8. Just read up on how to do it.

**Closed by oloflarsson** 2015-01-04 10:28 UTC
