### ISSUE TITLE
Faction doesn't work with Cauldron

### ISSUE THREAD

**Issue by Donitovan** [MassiveCraft/Factions#1111] opened 2016-06-23 18:29 UTC
I try desperately to run Faction with Cauldron 1.7.10 but no version of faction works! Would it be possible to have a compatible version? Thank you ! (i'm from france !)

**Comment by MarkehMe** [comment] 2016-06-24 01:59
Duplicate of #940

**Closed by MarkehMe** 2016-06-24 01:59 UTC
