### ISSUE TITLE
Error enabling MassiveCore v2.11.0 with PaperSpigot

### ISSUE THREAD

**Issue by Standfford** [MassiveCraft/Factions#1221] opened 2017-06-07 21:32 UTC
## Affected Plugin
- **Affected Plugin Name:** Factions and Massivecore

## Error in console
https://pastebin.com/5xHVNqVy

## Version
CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by MarkehMe** [comment] 2017-06-10 01:53
Although this is a duplicate of #1220 we're going to stick to this ticket as its better written.

**Comment by ulumulu1510** [comment] 2017-07-02 20:15
This issue has been resolved in the latest version (2.13), please update and it will be all good.

**Closed by ulumulu1510** 2017-07-02 20:15 UTC
Labels: Bug
