### ISSUE TITLE
Feature Request - Disallow Claiming When Enemy is in Chunk

### ISSUE THREAD

**Issue by matagin** [MassiveCraft/Factions#209] opened 2013-01-11 21:35 UTC
I would to request the feature to disallow chunk claiming if enemies are in the same chunk. Basically this would check to see the player location and faction relationship and disable the ability to f claim, f claim radius, or f autoclaim if there are enemy factions in the same chunk.  The reason for this is that players on Factions-based raiding servers that have TNT disabled in wilderness, do not use water to cancel TNT explosions when firing cannons so they must build cannons in wilderness. If an enemy comes to that chunk, they can claim their cannon basically. Disabling this ability would be a great addition.  Thanks.

**Comment by magnusulf** [comment] 2015-12-23 22:59
Duplicate of #209

**Closed by magnusulf** 2015-12-23 22:59 UTC
