### ISSUE TITLE
New feature/potential bad game mechanic (specific access)

### ISSUE THREAD

**Issue by Takeon** [MassiveCraft/Factions#1012] opened 2016-02-01 09:48 UTC
As a player if I was wanting to kick someone from my faction I would want to remove ALL of their access to the faction

When a player leaves, gets kicked, etc from a faction they keep all of their specific chunk access given to that player. It would be really good to remove all that players access from within a faction that they were removed from. So this will ignore any other access that other factions have set that player and only remove access given by the faction they were removed from. 

This can be toggle-able in two ways. Either through a config setting or through a factions flag and let the players decide what happens to their access on removal. Alternatives can be non-toggle or always remove access on /leave and after the automatic removal timer and then on /kick you can optionally add an argument to remove the access or not via /kick playername yes/no, default being yes

**Comment by magnusulf** [comment] 2016-02-01 18:12
Duplicate of #457

**Closed by magnusulf** 2016-02-01 18:12 UTC
