### ISSUE TITLE
Claiming Land

### ISSUE THREAD

**Issue by JunoCentral** [MassiveCraft/Factions#960] opened 2015-10-31 23:26 UTC
I get this error when trying to claim: https://gyazo.com/ce8504b0f129bf3e0328745439206c69

We are running the 1.7.10 modpack and using the latest version of factions. Not sure how to resolve this.

**Comment by MarkehMe** [comment] 2015-11-01 01:35
Thanks for reporting this issue! Let's see what we can do. 

* What version of Factions and MassiveCore are you using?
* Have you tried restarting the server, does the issue still arise then? 
* Did you reload the server?
* Did you load the plugin using PlugMan or another plugin manager?

**Comment by JunoCentral** [comment] 2015-11-01 01:43
I was using the latest version of factions and massivecore.

I have restarted the server several times, I believe claiming became an issue the first time I restarted server after downloading factions. But the initial time having it downloaded, claiming was fine. After restarting server, things went wrong.

I did not reload the server.

I believe I did use plugman when loading factions.

I will try to reproduce the issue. Will have to delete factions and redownload, etc. Will keep you posted.

**Comment by MarkehMe** [comment] 2015-11-01 01:48
Can you double check the version? Running ```/f version``` and ```/mcore version``` in your console will output the version. The versions need to be matching :) 

If you used plugman to load and then load them it may have caused some issues.

**Comment by JunoCentral** [comment] 2015-11-01 02:03
They are both version 2.8.0. Just like I thought, it happened again. I installed both again, they ran smoothly initially. However, once I restarted the server, they ran into problems with claiming. :/

**Comment by ulumulu1510** [comment] 2015-11-01 09:19
I will make a guess here:
Are you using Cauldron or KCauldron? Because those are know for an issue known as "Commansender-link severed" and it sounds alot like the problems you are facing. Could you confirm whether or not you are using cauldron?

**Comment by JunoCentral** [comment] 2015-11-01 13:21
I'm using cauldron.

**Comment by JunoCentral** [comment] 2015-11-01 16:11
It's actually Kcauldron*!

**Comment by ulumulu1510** [comment] 2015-11-01 19:35
At the current state we do not support cauldron/kcauldron. They have made some changes we are not fully able to follow and neither of the team has yet had the time/motivation to dig through all the files of cauldron to find the issue. Also we are focussing on developement for spigot, as we try to support the latest versions of it we are using ourselfs..

**Comment by MarkehMe** [comment] 2015-11-03 00:46
Duplicate of #940

**Closed by MarkehMe** 2015-11-03 00:46 UTC
