### ISSUE TITLE
FactionsDynmap 2.11.0 problem :-(

### ISSUE THREAD

**Issue by Uranusak** [MassiveCraft/Factions#1225] opened 2017-06-09 22:29 UTC
OpenJDK Runtime Environment (build 1.8.0_131-b12)
Spigot git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
Factions 2.11.0
Massivecore 2.11.0
FactionsDynmap 2.11.0
Dynmap 2.4
`[FactionsDynmap] Plugin FactionsDynmap v2.11.0 generated an exception while executing task 98 java.lang.NullPointerException at java.lang.String.replace(String.java:2240) ~[?:1.8.0_131] at com.massivecraft.factionsdynmap.EngineMain.getDescription(EngineMain.java:745) ~[?:?] at com.massivecraft.factionsdynmap.EngineMain.createHomes(EngineMain.java:259) ~[?:?] at com.massivecraft.factionsdynmap.EngineMain.run(EngineMain.java:125) ~[?:?] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-3fb9445-6e3cec8] at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-3fb9445-6e3cec8] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]`

**Comment by ncf1** [comment] 2017-06-09 22:33
this is identical to #1224

**Comment by MarkehMe** [comment] 2017-06-10 01:49
Duplicate of #1224

**Closed by MarkehMe** 2017-06-10 01:49 UTC
