### ISSUE TITLE
Problem with safezone and Fire Aspect

### ISSUE THREAD

**Issue by Whurauk** [MassiveCraft/Factions#1042] opened 2016-03-05 02:17 UTC
Hi, I recently download the new version of faction for the 1.9 and I saw that now the player with a fire aspect enchantment on their sword they can produce fire damage on others players. Here is a little video to show the bug :) Have a good day !

[Here is the video !](https://youtu.be/Hes_LjkDWIU)

**Comment by ItsMonkeyyy** [comment] 2016-03-05 03:55
Well this is a major issue. I will experiment tomorrow to see what the problem is. Currently 7:55PM (Pacific Standard Time) when I'm posting this. 

Could you also please provide the version of Factions that you're running? Please don't say "the latest one" thank you for your report :)

**Comment by Whurauk** [comment] 2016-03-05 04:06
Yes it is a major issue ! ahah! The version of the faction plugin I am running at this moment was the : 2.8.7Beta - Supports 1.9

Thanks for your quick answer ! :)

**Comment by ItsMonkeyyy** [comment] 2016-03-05 04:07
No problem, thank you for the information. I will look into this further tomorrow.

**Comment by ulumulu1510** [comment] 2016-03-05 07:58
Thak you for reporting this and thank you for the video showing the bug ingame.

It seems something must have changed how potion effects are applied now.

Please tell us what version of spigot you are using and the day it was built. And before reporting back, please re-run the buildtools (if you use 1.9l) because the bug could be serverside and thus be fixed already :)

Thanks

**Comment by Whurauk** [comment] 2016-03-05 14:22
I built spigot yesterday (2016-03-04) and it is spigot 1.9 from the BuildTools #4​9 release the
Mar 1, 2016 8:11 AM.

I just built spigot again and the same occurs. Thanks for your time ! :)

**Comment by oloflarsson** [comment] 2016-03-07 08:38
@ulumulu1510 - You wrote "potion effects" but @ItsMonkeyyy is talking about enchantments.

@ItsMonkeyyy - So do I understand the situation correctly:
You equip a weapon with the fire aspect enchantment. Then you hit someone in a place where PvP is not allowed, say for example the Safe Zone Faction. Upon hitting the player will take no damage, but the fire enchantment still goes through even if the damage is cancelled?

Or do the player on the receiving end take standard weapon damage too?

**Comment by Whurauk** [comment] 2016-03-07 12:47
It's exactly that, yes it's about enchantments sorry. When the playsr is hitting he will take no damage from the sword, only from the fire aspect enchantment as seen in the video.

**Comment by Whurauk** [comment] 2016-03-09 00:59
Does a fix will be release soon ?

**Comment by ItsMonkeyyy** [comment] 2016-03-09 05:16
@oloflarsson The actual damage from the sword does not register, the event gets cancelled, however DamageCause.FIRE_TICK does fire for some reason. I tried looking for a solution but I haven't had as much time lately. 

@Whurauk Hopefully a fix will come out soon

**Comment by ulumulu1510** [comment] 2016-03-10 17:40
I did some more research on this topic: We can't resolve it, it is a Spigot issue. For all those who have a JIRA account:
https://hub.spigotmc.org/jira/browse/SPIGOT-1813

I hope this will be fixed soon.

**Comment by ulumulu1510** [comment] 2016-03-14 16:37
Bug should be fixed by now. Re-run buildtools everyone.

**Closed by ulumulu1510** 2016-03-14 16:37 UTC
Labels: Bug
