### ISSUE TITLE
PvP not working

### ISSUE THREAD

**Issue by McIsTheLimit** [MassiveCraft/Factions#981] opened 2015-12-01 01:57 UTC
Hello,

I am running a network, and on our Factions server, out of nowhere, PvP stopped working except for ops, and I don't know why. I have tested it with me along with the other owner, where I opped and deoped myself and tried to hit him worked, we tried hitting a normal player, it didn't work, we tried it in the pvp arena in a different work, still didn't work, we tried in the wild, didn't work, and we even tried resetting the factions config as well.

Please help

Best regards,
McIsTheLimit

**Comment by McIsTheLimit** [comment] 2015-12-01 01:58
nvm soled!

**Comment by MarkehMe** [comment] 2015-12-07 00:35
It's common for these issue tickets to show up in search engine results, do you mind letting the internet know how you fixed it? :-)

**Comment by McIsTheLimit** [comment] 2015-12-07 14:39
I really don't know, it sometimes works, and other times it doesn't, I've went through trial and error and I the same thing happens. I'll keep looking for the answer, and when I find it, or anyone for that matter, I'll make sure to get the word out :+1: :)

**Comment by magnusulf** [comment] 2016-01-09 10:31
No longer relevant. Issue could've been caused by external plugins. Closing.

**Closed by magnusulf** 2016-01-09 10:31 UTC
