### ISSUE TITLE
/f claim square 50

### ISSUE THREAD

**Issue by Loonytoon1997** [MassiveCraft/Factions#950] opened 2015-10-11 20:21 UTC
http://pastebin.com/XpWAAgjP error log

**Comment by MarkehMe** [comment] 2015-10-11 22:57
Please provide your version of Factions and your version of MassiveCore!

**Comment by Loonytoon1997** [comment] 2015-10-12 00:58
I have the latest versions of everything.

**Comment by MarkehMe** [comment] 2015-10-12 02:12
Please just provide the version. Also, what version of Java?

**Comment by Loonytoon1997** [comment] 2015-10-13 01:04
Factions: 2.8.1
MassiveCore: 2.8.1
Java: 8

**Comment by ulumulu1510** [comment] 2015-10-13 05:26
Could it be that your servers claiming max (that is a config option)  is smaller than 50? 
There are two ways of pss getting to be null at that point of the programm, this is one of them. the other is very unlikely from your command input.

**Comment by magnusulf** [comment] 2015-12-26 00:58
Duplicate of #910

**Closed by magnusulf** 2015-12-26 00:58 UTC
Labels: Bug
