### ISSUE TITLE
Ally and Faction's Members Taking Damage

### ISSUE THREAD

**Issue by Faller10** [MassiveCraft/Factions#900] opened 2015-07-08 19:35 UTC
Hi!
So recently, my Factions plugin started to give me some annoying bugs! 
My players are complaining about there faction's members being able to pvp with themselves!
This is also happening to allys! Everyone is being able to pvp, but the plugin is working fine! 

I'm using Factions 2.7.5
MassiveCore 2.7.5

**Comment by Coolaxer** [comment] 2015-10-02 05:40
I can confirm this. Can you please provide the version of spigot/cauldron/craftbukkit you are running? On my cauldron server, it seems as though players can kill their allys. With faction members, they can repetedly hit them, and neither of them take damage, but the attacker fills up with xp

**Comment by oloflarsson** [comment] 2015-10-20 15:22
Cauldron is not supported at the moment. So if you are using Cauldron you can expect loads of different bugs and feature failures.

**Comment by magnusulf** [comment] 2015-12-26 00:57
This seems to be caused by Cauldron usage. Cauldron is not supported. Closing.

**Closed by magnusulf** 2015-12-26 00:57 UTC
Labels: Help
